TebLocalPlannerROS:

  odom_topic: odom
  # map_frame: /map

# Trajectory

  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: False
  max_global_plan_lookahead_dist: 2.0
  feasibility_check_no_poses: 3

# Robot

  max_vel_x: 1.3
  max_vel_x_backwards: 1.1
  max_vel_y: 0.0
  max_vel_theta: 2.9
  acc_lim_x: 1.5
  acc_lim_theta: 3.3

  # ********************** Carlike robot parameters ********************
  min_turning_radius: 0.25  #最小转向半径
  # heelbase: 0.4                 # Wheelbase of our robot
  # cmd_angle_instead_rotvel: True # stage simulator takes the angle instead of the rotvel as input (twist message)
  # ********************************************************************


  footprint_model:
    type: "polygon"
    vertices: [[0.171, -0.128], [0.171, 0.128],[-0.171, 0.128], [-0.171, -0.128]]


# GoalTolerance

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.5
  free_goal_vel: False

# Obstacles

  min_obstacle_dist: 0.2 # This value must also include our robot radius, since footprint_model is set to "point".
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 15

  inflation_dist: 1
  dynamic_obstacle_inflation_dist: 1
  include_dynamic_obstacles: True
  

  #此部分在costmap_converter_params.yaml中表述
  # costmap_converter_plugin: ""
  # costmap_converter_spin_thread: true
  # costmap_converter_rate: 5.0

  
  # costmap_converter parameters are defined in costmap_converter_params.yaml

# Optimization

  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.05
  weight_max_vel_x: 100
  weight_max_vel_theta: 1.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_theta: 1.0
  weight_kinematics_nh: 1000.0
  weight_kinematics_forward_drive: 1000.0
  weight_kinematics_turning_radius: 150.0
  weight_optimaltime: 50
  # weight_shortest_path: 0
  weight_obstacle: 50
  weight_inflation: 0.1
  weight_dynamic_obstacle: 50
  weight_dynamic_obstacle_inflation: 0.3
  weight_viapoint: 1.0  #优化过程中，和全局路径采样点距离的权重  0-1000
  weight_adapt_factor: 2

  # Homotopy Class Planner

  enable_homotopy_class_planning: True
  enable_multithreading: True
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  # selection_prefer_initial_plan: 0.95
  selection_obst_cost_scale: 100.0
  selection_alternative_time_cost: True

  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  # roadmap_graph_area_length_scale: 1.0
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  switching_blocking_period: 0.0
  viapoints_all_candidates: true
  # delete_detours_backwards: True
  # max_ratio_detours_duration_best_duration: 3.0
  visualize_hc_graph: False
  visualize_with_time_as_z_axis_scale: 0.2


# Recovery

  shrink_horizon_backup: true  #当规划器检测到系统异常，允许缩小时域规划范围。
  shrink_horizon_min_duration: 10.0
  # oscillation_recovery: True
  # oscillation_v_eps: 0.1
  # oscillation_omega_eps: 0.1
  # oscillation_recovery_min_duration: 10
  # oscillation_filter_duration: 10


  # force_reinit_new_goal_dist: 1.0  
  # is_footprint_dynamic: True
  # legacy_obstacle_association: false
  # obstacle_association_force_inclusion_factor: 1.5
  # obstacle_association_cutoff_factor: 5
  # selection_viapoint_cost_scale: 1.0